name = "morphir_cli"
version = "0.1.0"
description = "Morphir CLI tooling for Gleam"
licences = ["Apache-2.0"]
target = "erlang"

[repository]
type = "github"
user = "finos"
repo = "morphir-gleam"
path = "packages/morphir_cli"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
glint = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
morphir_models = { path = "../morphir_models" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
